'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Locale = 'en' | 'sv' | 'ar';
const DEFAULT_LOCALE: Locale = 'en';
const isLocale = (value: string): value is Locale => value === 'en' || value === 'sv' || value === 'ar';
const normalizeLocale = (value: string): Locale => (isLocale(value) ? value : DEFAULT_LOCALE);

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const translations: Record<Locale, Record<string, string>> = {
  sv: {
    // Navigation
    'nav.home': 'Hem',
    'nav.about': 'Om oss',
    'nav.courses': 'Kurser',
    'nav.events': 'Evenemang',
    'nav.getInvolved': 'Engagera dig',
    'nav.contact': 'Kontakt',

    // Hero
    'hero.title': 'KlickIT',
    'hero.subtitle': 'Digital kompetens för alla åldrar',
    'hero.description': 'Vi bygger broar mellan människor och digitala verktyg',
    'hero.cta': 'Börja lära dig',
    'hero.learnMore': 'Läs mer',

    // Stats
    'stats.workshops': 'Workshops',
    'stats.students': 'Elever',
    'stats.volunteers': 'Frivilliga',
    'stats.partners': 'Partners',

    // About
    'about.title': 'Om oss',
    'about.subtitle': 'Vår mission och vision',
    'about.description': 'KlickIT är en nybildad ideell förening (startad 2025-07-07) av engagerade föräldrar. Vi är oroade över att många barn, unga och äldre inte klarar att navigera den digitala världen.',
    'about.mission': 'Vi skapar trygga vägar till digital kompetens och arbetar för ett hälsosamt, effektivt och meningsfullt digitalt liv – för alla åldrar.',
    'about.vision': 'Vi drömmer om en värld där alla, oavsett ålder, kan känna sig trygga och kreativa i den digitala världen.',
    'about.values': 'Våra värderingar',
    'about.inclusion': 'Inkludering',
    'about.inclusion.desc': 'Digital kompetens ska vara tillgänglig för alla',
    'about.innovation': 'Innovation',
    'about.innovation.desc': 'Vi utforskar nya sätt att lära och växa',
    'about.community': 'Gemenskap',
    'about.community.desc': 'Tillsammans är vi starkare',

    // What We Do
    'whatwedo.title': 'Vad vi gör',
    'whatwedo.subtitle': 'Våra initiativ för en digital framtid',
    'whatwedo.workshops.title': 'Workshops i digital kompetens',
    'whatwedo.workshops.description': 'Praktiska workshops som ger verktyg för att navigera den digitala världen med självförtroende.',
    'whatwedo.courses.title': 'Kurser för alla åldrar',
    'whatwedo.courses.description': 'Anpassade kurser för barn, unga och vuxna som bygger digital förståelse steg för steg.',
    'whatwedo.collaboration.title': 'Samarbete med skolor & IT-branschen',
    'whatwedo.collaboration.description': 'Vi skapar broar mellan utbildning och näringsliv för bättre digital kompetens.',
    'whatwedo.elderly.title': 'Digitalt stöd till äldre',
    'whatwedo.elderly.description': 'Särskilt fokus på att hjälpa äldre att känna sig trygga med digital teknik.',
    'whatwedo.focus.title': 'Fokus på hälsa, vardag, framtida yrken',
    'whatwedo.focus.description': 'Vi kopplar digital kompetens till verkliga behov i vardagen och framtiden.',
    'whatwedo.parents.title': 'Nära samarbete med engagerade föräldrar',
    'whatwedo.parents.description': 'Vi involverar föräldrar och ungdomar aktivt i föreningens utvecklingsarbete.',

    // Contact
    'contact.title': 'Kontakt',
    'contact.subtitle': 'Vi hör gärna från dig',
    'contact.description': 'Har du frågor eller vill samarbeta? Tveka inte att kontakta oss.',
    'contact.cta': 'Vill du samarbeta, bidra eller bara säga hej? Hör gärna av dig.',
    'contact.email': 'E-post',
    'contact.address': 'Adress',
    'contact.addressContent': 'Stockholm, Sverige',
    'contact.social': 'Sociala medier',
    'contact.form.title': 'Skicka ett meddelande',
    'contact.form.name': 'Namn',
    'contact.form.email': 'E-post',
    'contact.form.subject': 'Ämne',
    'contact.form.message': 'Meddelande',
    'contact.form.selectSubject': 'Välj ämne',
    'contact.form.subjects.general': 'Allmän fråga',
    'contact.form.subjects.courses': 'Kurser',
    'contact.form.subjects.volunteer': 'Engagera dig',
    'contact.form.subjects.partner': 'Samarbete',
    'contact.form.subjects.other': 'Annat',
    'contact.form.submit': 'Skicka meddelande',
    'contact.form.success': 'Tack för ditt meddelande!',
    'contact.form.successText': 'Vi återkommer så snart som möjligt.',
    'contact.faq': 'Vanliga frågor',
    'contact.tip': 'Tips',
    'contact.tipText': 'Vi svarar vanligtvis inom 24 timmar på alla förfrågningar.',
    'contact.closing': 'Bygg broar till den digitala världen',
    'contact.closingText': 'KlickIT är din partner för digital kompetens. Vi tror på en värld där alla kan delta i det digitala samhället.',

    // FAQ
    'faq.q1': 'Hur kan jag bli volontär?',
    'faq.a1': 'Fyll i intresseanmälan på sidan "Engagera dig" så kontaktar vi dig inom 48 timmar.',
    'faq.q2': 'Kostar det något att delta i workshops?',
    'faq.a2': 'Nej, alla våra workshops och kurser är helt gratis tack vare våra sponsorer och donatorer.',
    'faq.q3': 'Vilka åldersgrupper riktar ni er till?',
    'faq.a3': 'Vi välkomnar alla åldrar! Vi har särskilda program för barn (8-16), vuxna och seniorer (65+).',
    'faq.q4': 'Var håller ni till?',
    'faq.a4': 'Vi har aktiviteter både online och på olika platser i Stockholm. Kolla kalendern för aktuella datum.',

    // Courses Page
    'courses.title': 'Våra Kurser',
    'courses.subtitle': 'Lär dig digitala färdigheter på ditt sätt',
    'courses.cta': 'Läs mer & anmäl dig',
    'courses.beginner': 'Nybörjare',
    'courses.intermediate': 'Medel',
    'courses.advanced': 'Avancerad',
    'courses.howItWorks': 'Så här fungerar det',
    'courses.steps.register': 'Registrera dig',
    'courses.steps.choose': 'Välj kurs',
    'courses.steps.learn': 'Lär dig',
    'courses.steps.grow': 'Växa',
    'courses.faq': 'Vanliga frågor',
    'courses.faq.q1': 'Vilka förkunskaper behövs?',
    'courses.faq.a1': 'Inga förkunskaper krävs för våra nybörjarkurser. Vi börjar från grunden!',
    'courses.faq.q2': 'Hur långa är kurserna?',
    'courses.faq.a2': 'De flesta kurser är mellan 4-10 veckor med 1-2 tillfällen per vecka.',
    'courses.faq.q3': 'Kan jag delta online?',
    'courses.faq.a3': 'Ja, många av våra kurser erbjuds både fysiskt och online.',
    'courses.ctaTitle': 'Redo att börja din digitala resa?',
    'courses.ctaText': 'Gå med i vår gemenskap och lär dig nya färdigheter tillsammans med oss',

    // Events Page
    'events.title': 'Evenemang',
    'events.subtitle': 'Delta i våra aktiviteter och workshops',
    'events.upcoming': 'Kommande evenemang',
    'events.past': 'Tidigare evenemang',
    'events.register': 'Anmäl dig',
    'events.suggest': 'Föreslå en aktivitet',
    'events.volunteer': 'Bli volontär',
    'events.ctaTitle': 'Vill du hålla i en aktivitet?',
    'events.ctaText': 'Vi tar gärna emot dina idéer för framtida evenemang och samarbeten.',

    // Get Involved Page
    'getInvolved.title': 'Engagera dig',
    'getInvolved.subtitle': 'Bli en del av rörelsen',
    'getInvolved.description': 'Tillsammans kan vi göra skillnad. Det finns många sätt att bidra till KlickITs verksamhet.',
    'getInvolved.volunteer.title': 'Bli volontär',
    'getInvolved.volunteer.description': 'Dela din kunskap och hjälp andra att växa digitalt. Vi behöver mentorer, workshopsledare och projektledare.',
    'getInvolved.volunteer.benefit1': 'Flexibla timmar',
    'getInvolved.volunteer.benefit2': 'Värdefull erfarenhet',
    'getInvolved.volunteer.benefit3': 'Nätverkande möjligheter',
    'getInvolved.donate.title': 'Donera',
    'getInvolved.donate.description': 'Ditt bidrag hjälper oss att nå fler människor och erbjuda gratis kurser till dem som behöver det mest.',
    'getInvolved.donate.benefit1': '100 kr = 1 barn får en komplett kurs',
    'getInvolved.donate.benefit2': 'Bidra till digital inkludering',
    'getInvolved.donate.benefit3': 'Gör skillnad i ditt samhälle',
    'getInvolved.partner.title': 'Samarbeta',
    'getInvolved.partner.description': 'Företag och organisationer kan samarbeta med oss för att skapa meningsfulla digitala utbildningsprojekt.',
    'getInvolved.partner.benefit1': 'CSR-projekt med impact',
    'getInvolved.partner.benefit2': 'Praktikplatser för unga',
    'getInvolved.partner.benefit3': 'Utvecklingsmöjligheter för anställda',
    'getInvolved.school.title': 'Skolsamarbete',
    'getInvolved.school.description': 'Vi samarbetar med skolor för att erbjuda digital utbildning till elever och lärare.',
    'getInvolved.school.benefit1': 'Kompletterande undervisning',
    'getInvolved.school.benefit2': 'Lärarfortbildning',
    'getInvolved.school.benefit3': 'Elevprojekt och workshops',
    'getInvolved.cta': 'Kontakta oss',
    'getInvolved.ctaTitle': 'Redo att göra skillnad?',
    'getInvolved.ctaText': 'Gå med i vår gemenskap och hjälp oss bygga broar till den digitala världen.',
    'getInvolved.join': 'Gå med nu',

    // Values
    'values.subtitle': 'Vad vi står för',
    'values.title': 'Våra värderingar',
    'values.description': 'Vi tror på en värld där alla kan delta i det digitala samhället.',
    'values.inclusion.title': 'Stöd',
    'values.inclusion.desc': 'Vi stöttar alla som vill lära sig digitala färdigheter',
    'values.innovation.title': 'Innovation',
    'values.innovation.desc': 'Vi utforskar nya sätt att lära och växa tillsammans',
    'values.community.title': 'Gemenskap',
    'values.community.desc': 'Tillsammans är vi starkare i den digitala världen',
    'values.learning.title': 'Lärande',
    'values.learning.desc': 'Vi tror på livslångt lärande för alla åldrar',

    // Footer
    'footer.description': 'Vi bygger broar mellan människor och digitala verktyg. Digital kompetens för alla åldrar.',
    'footer.explore': 'Utforska',
    'footer.contact': 'Kontakt',
    'footer.location': 'Stockholm, Sverige',
    'footer.newsletter': 'Nyhetsbrev',
    'footer.newsletterText': 'Få senaste nytt om våra kurser och evenemang',
    'footer.emailPlaceholder': 'Din e-post',
    'footer.subscribe': 'Prenumerera',
    'footer.rights': 'Alla rättigheter reserverade.',
    'footer.privacy': 'Integritetspolicy',
    'footer.terms': 'Villkor',

    // Extra
    'about.learnMore': 'Läs mer om oss',
    'whatwedo.description': 'Vi arbetar för att göra den digitala världen tillgänglig för alla',
    'tags.education': 'Digital utbildning',
    'tags.community': 'Gemenskap',
    'tags.inclusion': 'Inkludering',
    'tags.innovation': 'Innovation',
    'org.badge': 'Vår organisation',
    'org.title': 'Strukturerad för påverkan',
    'org.description': 'Vi är organiserade för att effektivt förverkliga vårt uppdrag om digital inkludering för alla.',
    'org.dept.edu.title': 'Digital Utbildning',
    'org.dept.edu.desc': 'Utvecklar kursplaner och pedagogiska workshops.',
    'org.dept.community.title': 'Samhällsengagemang',
    'org.dept.community.desc': 'Bygger relationer med lokalsamhället och partners.',
    'org.dept.support.title': 'Teknisk Support',
    'org.dept.support.desc': 'Erbjuder praktisk hjälp och teknisk vägledning.',
    'org.dept.innovation.title': 'Innovationslabb',
    'org.dept.innovation.desc': 'Utforskar nya teknologier och digitala verktyg.',

    'course.1.title': 'Digitala grunderna för barn',
    'course.1.desc': 'En introduktion till datorer, internet och säkerhet på nätet för barn 8-12 år.',
    'course.1.duration': '6 veckor',
    'course.1.age': '8-12 år',
    'course.2.title': 'Digital kompetens för unga',
    'course.2.desc': 'Fördjupning i sociala medier, kreativt skapande och framtidens arbetsmarknad.',
    'course.2.duration': '8 veckor',
    'course.2.age': '13-18 år',
    'course.3.title': 'Digitala verktyg för vuxna',
    'course.3.desc': 'Praktiska färdigheter i e-post, videomöten, dokumenthantering och online-tjänster.',
    'course.3.duration': '4 veckor',
    'course.3.age': '18+ år',
    'course.4.title': 'Digital trygghet för seniorer',
    'course.4.desc': 'En skräddarsydd kurs för att känna sig trygg med smartphones, surfplattor och internet.',
    'course.4.duration': '6 veckor',
    'course.4.age': '65+ år',
    'course.5.title': 'Kreativt skapande digitalt',
    'course.5.desc': 'Lär dig bildredigering, videoframställning och musikproduktion med moderna verktyg.',
    'course.5.duration': '10 veckor',
    'course.5.age': '12+ år',
    'course.6.title': 'Digitalt arbete och karriär',
    'course.6.desc': 'Kompetenser för att navigera arbetsmarknaden och använda digitala verktyg i yrkeslivet.',
    'course.6.duration': '8 veckor',
    'course.6.age': '16+ år',
    'event.1.title': 'Digital säkerhet för föräldrar',
    'event.1.desc': 'Lär dig hur du kan skydda dina barn på nätet och förstå deras digitala värld.',
    'event.1.location': 'Biblioteket, Centralt',
    'event.2.title': 'Introduktion till AI för nybörjare',
    'event.2.desc': 'En grundläggande introduktion till artificiell intelligens och hur den påverkar vårt dagliga liv.',
    'event.2.location': 'Kulturhuset, Sal 3',
    'event.3.title': 'Kodning för barn (Årskurs 3-6)',
    'event.3.desc': 'Lär dig grunderna i programmering med roliga och enkla övningar.',
    'event.3.location': 'TechHub, Main Hall',
    'event.4.title': 'Sociala medier - Fördelar och risker',
    'event.4.desc': 'En öppen diskussion om sociala mediers påverkan på ungdomar och hur man använder dem ansvarsfullt.',
    'event.4.location': 'Medborgarhuset',
    'event.5.title': 'Smartphone-kurs för seniorer',
    'event.5.desc': 'En nybörjarkurs anpassad för dig som vill lära dig använda din smartphone bättre.',
    'event.5.location': 'Seniorcentret',
    'event.type.workshop': 'Workshop',
    'event.type.lecture': 'Föreläsning',
    'event.type.discussion': 'Diskussion',
    'event.type.course': 'Kurs',

    'event.past.1.title': 'Kickoff - Vi bygger broar',
    'event.past.1.desc': 'Föreningens officiella lansering med tal, mingel och framtidsvisioner.',
    'event.past.2.title': 'Sommarkodläger för ungdomar',
    'event.past.2.desc': 'Fem dagar fullspäckade med programmering, spelutveckling och digitalt skapande.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About us',
    'nav.courses': 'Courses',
    'nav.events': 'Events',
    'nav.getInvolved': 'Get Involved',
    'nav.contact': 'Contact',

    // Hero
    'hero.title': 'KlickIT',
    'hero.subtitle': 'Digital skills for all ages',
    'hero.description': 'We build bridges between people and digital tools',
    'hero.cta': 'Start Learning',
    'hero.learnMore': 'Learn More',

    // Stats
    'stats.workshops': 'Workshops',
    'stats.students': 'Students',
    'stats.volunteers': 'Volunteers',
    'stats.partners': 'Partners',

    // About
    'about.title': 'About us',
    'about.subtitle': 'Our mission and vision',
    'about.description': 'KlickIT is a newly formed non-profit association (started 2025-07-07) by engaged parents. We are concerned that many children, young people, and elderly struggle to navigate the digital world.',
    'about.mission': 'We create safe paths to digital competence and work towards a healthy, effective, and meaningful digital life – for all ages.',
    'about.vision': 'We dream of a world where everyone, regardless of age, can feel safe and creative in the digital world.',
    'about.values': 'Our Values',
    'about.inclusion': 'Inclusion',
    'about.inclusion.desc': 'Digital skills should be accessible to everyone',
    'about.innovation': 'Innovation',
    'about.innovation.desc': 'We explore new ways to learn and grow',
    'about.community': 'Community',
    'about.community.desc': 'Together we are stronger',

    // What We Do
    'whatwedo.title': 'What We Do',
    'whatwedo.subtitle': 'Our initiatives for a digital future',
    'whatwedo.workshops.title': 'Digital Skills Workshops',
    'whatwedo.workshops.description': 'Practical workshops that provide tools to navigate the digital world with confidence.',
    'whatwedo.courses.title': 'Courses for All Ages',
    'whatwedo.courses.description': 'Tailored courses for children, young people, and adults that build digital understanding step by step.',
    'whatwedo.collaboration.title': 'Collaboration with Schools & IT Industry',
    'whatwedo.collaboration.description': 'We create bridges between education and business for better digital competence.',
    'whatwedo.elderly.title': 'Digital Support for the Elderly',
    'whatwedo.elderly.description': 'Special focus on helping elderly feel confident with digital technology.',
    'whatwedo.focus.title': 'Focus on Health, Everyday Life, Future Careers',
    'whatwedo.focus.description': 'We connect digital skills to real needs in everyday life and the future.',
    'whatwedo.parents.title': 'Close Collaboration with Engaged Parents',
    'whatwedo.parents.description': 'We actively involve parents and young people in the association\'s development work.',

    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': "We'd love to hear from you",
    'contact.description': 'Do you have questions or want to collaborate? Feel free to reach out.',
    'contact.cta': "Want to collaborate, contribute, or just say hi? Feel free to reach out.",
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.addressContent': 'Stockholm, Sweden',
    'contact.social': 'Social Media',
    'contact.form.title': 'Send a Message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.selectSubject': 'Select a subject',
    'contact.form.subjects.general': 'General inquiry',
    'contact.form.subjects.courses': 'Courses',
    'contact.form.subjects.volunteer': 'Get Involved',
    'contact.form.subjects.partner': 'Partnership',
    'contact.form.subjects.other': 'Other',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Thank you for your message!',
    'contact.form.successText': 'We will get back to you as soon as possible.',
    'contact.faq': 'Frequently Asked Questions',
    'contact.tip': 'Tip',
    'contact.tipText': 'We usually respond within 24 hours to all inquiries.',
    'contact.closing': 'Building bridges to the digital world',
    'contact.closingText': 'KlickIT is your partner for digital competence. We believe in a world where everyone can participate in the digital society.',

    // FAQ
    'faq.q1': 'How can I become a volunteer?',
    'faq.a1': 'Fill out the interest form on the "Get Involved" page and we will contact you within 48 hours.',
    'faq.q2': 'Does it cost anything to attend workshops?',
    'faq.a2': 'No, all our workshops and courses are completely free thanks to our sponsors and donors.',
    'faq.q3': 'What age groups do you target?',
    'faq.a3': 'We welcome all ages! We have special programs for children (8-16), adults, and seniors (65+).',
    'faq.q4': 'Where do you hold activities?',
    'faq.a4': 'We have activities both online and at various locations in Stockholm. Check the calendar for current dates.',

    // Courses Page
    'courses.title': 'Our Courses',
    'courses.subtitle': 'Learn digital skills your way',
    'courses.cta': 'Learn More & Enroll',
    'courses.beginner': 'Beginner',
    'courses.intermediate': 'Intermediate',
    'courses.advanced': 'Advanced',
    'courses.howItWorks': 'How It Works',
    'courses.steps.register': 'Register',
    'courses.steps.choose': 'Choose Course',
    'courses.steps.learn': 'Learn',
    'courses.steps.grow': 'Grow',
    'courses.faq': 'FAQ',
    'courses.faq.q1': 'What prerequisites are needed?',
    'courses.faq.a1': 'No prerequisites are required for our beginner courses. We start from the basics!',
    'courses.faq.q2': 'How long are the courses?',
    'courses.faq.a2': 'Most courses are between 4-10 weeks with 1-2 sessions per week.',
    'courses.faq.q3': 'Can I participate online?',
    'courses.faq.a3': 'Yes, many of our courses are offered both in-person and online.',
    'courses.ctaTitle': 'Ready to start your digital journey?',
    'courses.ctaText': 'Join our community and learn new skills together with us',

    // Events Page
    'events.title': 'Events',
    'events.subtitle': 'Join our activities and workshops',
    'events.upcoming': 'Upcoming Events',
    'events.past': 'Past Events',
    'events.register': 'Register',
    'events.suggest': 'Suggest an Activity',
    'events.volunteer': 'Become a Volunteer',
    'events.ctaTitle': 'Want to host an activity?',
    'events.ctaText': 'We welcome your ideas for future events and collaborations.',

    // Get Involved Page
    'getInvolved.title': 'Get Involved',
    'getInvolved.subtitle': 'Be part of the movement',
    'getInvolved.description': 'Together we can make a difference. There are many ways to contribute to KlickIT.',
    'getInvolved.volunteer.title': 'Become a Volunteer',
    'getInvolved.volunteer.description': 'Share your knowledge and help others grow digitally. We need mentors, workshop leaders, and project managers.',
    'getInvolved.volunteer.benefit1': 'Flexible hours',
    'getInvolved.volunteer.benefit2': 'Valuable experience',
    'getInvolved.volunteer.benefit3': 'Networking opportunities',
    'getInvolved.donate.title': 'Donate',
    'getInvolved.donate.description': 'Your contribution helps us reach more people and offer free courses to those who need it most.',
    'getInvolved.donate.benefit1': '100 SEK = 1 child gets a complete course',
    'getInvolved.donate.benefit2': 'Contribute to digital inclusion',
    'getInvolved.donate.benefit3': 'Make a difference in your community',
    'getInvolved.partner.title': 'Partner with Us',
    'getInvolved.partner.description': 'Businesses and organizations can collaborate with us to create meaningful digital education projects.',
    'getInvolved.partner.benefit1': 'CSR projects with impact',
    'getInvolved.partner.benefit2': 'Internships for youth',
    'getInvolved.partner.benefit3': 'Development opportunities for employees',
    'getInvolved.school.title': 'School Collaboration',
    'getInvolved.school.description': 'We collaborate with schools to offer digital education to students and teachers.',
    'getInvolved.school.benefit1': 'Complementary teaching',
    'getInvolved.school.benefit2': 'Teacher training',
    'getInvolved.school.benefit3': 'Student projects and workshops',
    'getInvolved.cta': 'Contact Us',
    'getInvolved.ctaTitle': 'Ready to make a difference?',
    'getInvolved.ctaText': 'Join our community and help us build bridges to the digital world.',
    'getInvolved.join': 'Join Now',

    // Values
    'values.subtitle': 'What we stand for',
    'values.title': 'Our Values',
    'values.description': 'We believe in a world where everyone can participate in the digital society.',
    'values.inclusion.title': 'Support',
    'values.inclusion.desc': 'We support everyone who wants to learn digital skills',
    'values.innovation.title': 'Innovation',
    'values.innovation.desc': 'We explore new ways to learn and grow together',
    'values.community.title': 'Community',
    'values.community.desc': 'Together we are stronger in the digital world',
    'values.learning.title': 'Learning',
    'values.learning.desc': 'We believe in lifelong learning for all ages',

    // Footer
    'footer.description': 'We build bridges between people and digital tools. Digital skills for all ages.',
    'footer.explore': 'Explore',
    'footer.contact': 'Contact',
    'footer.location': 'Stockholm, Sweden',
    'footer.newsletter': 'Newsletter',
    'footer.newsletterText': 'Get the latest news about our courses and events',
    'footer.emailPlaceholder': 'Your email',
    'footer.subscribe': 'Subscribe',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms',

    // Extra
    'about.learnMore': 'Learn more about us',
    'whatwedo.description': 'We work to make the digital world accessible to everyone',
    'tags.education': 'Digital Education',
    'tags.community': 'Community',
    'tags.inclusion': 'Inclusion',
    'tags.innovation': 'Innovation',
    'org.badge': 'Our organization',
    'org.title': 'Structured for impact',
    'org.description': 'We are organized to effectively realize our mission of digital inclusion for all.',
    'org.dept.edu.title': 'Digital Education',
    'org.dept.edu.desc': 'Developing curriculum and educational workshops.',
    'org.dept.community.title': 'Community Outreach',
    'org.dept.community.desc': 'Building relationships with local communities and partners.',
    'org.dept.support.title': 'Technical Support',
    'org.dept.support.desc': 'Providing hands-on assistance and technical guidance.',
    'org.dept.innovation.title': 'Innovation Lab',
    'org.dept.innovation.desc': 'Exploring new technologies and digital tools.',

    'course.1.title': 'Digital Basics for Children',
    'course.1.desc': 'An introduction to computers, the internet, and online safety for children 8-12 years old.',
    'course.1.duration': '6 weeks',
    'course.1.age': '8-12 years',
    'course.2.title': 'Digital Competence for Youth',
    'course.2.desc': 'Deepening in social media, creative creation, and the future labor market.',
    'course.2.duration': '8 weeks',
    'course.2.age': '13-18 years',
    'course.3.title': 'Digital Tools for Adults',
    'course.3.desc': 'Practical skills in email, video meetings, document management, and online services.',
    'course.3.duration': '4 weeks',
    'course.3.age': '18+ years',
    'course.4.title': 'Digital Safety for Seniors',
    'course.4.desc': 'A tailored course to feel confident with smartphones, tablets, and the internet.',
    'course.4.duration': '6 weeks',
    'course.4.age': '65+ years',
    'course.5.title': 'Creative Digital Creation',
    'course.5.desc': 'Learn image editing, video production, and music production with modern tools.',
    'course.5.duration': '10 weeks',
    'course.5.age': '12+ years',
    'course.6.title': 'Digital Work and Career',
    'course.6.desc': 'Competencies to navigate the labor market and use digital tools in professional life.',
    'course.6.duration': '8 weeks',
    'course.6.age': '16+ years',
    'event.1.title': 'Digital Safety for Parents',
    'event.1.desc': 'Learn how you can protect your children online and understand their digital world.',
    'event.1.location': 'The Library, Central',
    'event.2.title': 'Introduction to AI for Beginners',
    'event.2.desc': 'A basic introduction to artificial intelligence and how it affects our daily lives.',
    'event.2.location': 'Kulturhuset, Hall 3',
    'event.3.title': 'Coding for Children (Grades 3-6)',
    'event.3.desc': 'Learn the basics of programming with fun and simple exercises.',
    'event.3.location': 'TechHub, Main Hall',
    'event.4.title': 'Social Media - Benefits and Risks',
    'event.4.desc': "An open discussion about social media's impact on youth and how to use them responsibly.",
    'event.4.location': 'Medborgarhuset',
    'event.5.title': 'Smartphone Course for Seniors',
    'event.5.desc': 'A beginner course adapted for those who want to learn how to use their smartphone better.',
    'event.5.location': 'Senior Center',
    'event.type.workshop': 'Workshop',
    'event.type.lecture': 'Lecture',
    'event.type.discussion': 'Discussion',
    'event.type.course': 'Course',

    'event.past.1.title': 'Kickoff - Building Bridges',
    'event.past.1.desc': 'The association\'s official launch with speeches, mingling, and future visions.',
    'event.past.2.title': 'Summer Coding Camp for Youth',
    'event.past.2.desc': 'Five days packed with programming, game development, and digital creation.',
  },
  ar: {
    // Navigation
    'course.1.title': 'الأساسيات الرقمية للأطفال',
    'course.1.desc': 'مقدمة عن أجهزة الكمبيوتر والإنترنت والأمان عبر الإنترنت للأطفال من سن 8 إلى 12 عاماً.',
    'course.1.duration': '6 أسابيع',
    'course.1.age': '8-12 سنة',
    'course.2.title': 'الكفاءة الرقمية للشباب',
    'course.2.desc': 'تعمق في وسائل التواصل الاجتماعي، والابتكار الإبداعي، وسوق العمل في المستقبل.',
    'course.2.duration': '8 أسابيع',
    'course.2.age': '13-18 سنة',
    'course.3.title': 'الأدوات الرقمية للبالغين',
    'course.3.desc': 'مهارات عملية في البريد الإلكتروني، واجتماعات الفيديو، وإدارة المستندات، والخدمات عبر الإنترنت.',
    'course.3.duration': '4 أسابيع',
    'course.3.age': '18+ سنة',
    'course.4.title': 'الأمان الرقمي لكبار السن',
    'course.4.desc': 'دورة مخصصة للشعور بالثقة مع الهواتف الذكية والأجهزة اللوحية والإنترنت.',
    'course.4.duration': '6 أسابيع',
    'course.4.age': '65+ سنة',
    'course.5.title': 'الابتكار الرقمي الإبداعي',
    'course.5.desc': 'تعلم تحرير الصور، وإنتاج الفيديو، وإنتاج الموسيقى باستخدام الأدوات الحديثة.',
    'course.5.duration': '10 أسابيع',
    'course.5.age': '12+ سنة',
    'course.6.title': 'العمل الرقمي والمسار المهني',
    'course.6.desc': 'كفاءات للتنقل في سوق العمل واستخدام الأدوات الرقمية في الحياة المهنية.',
    'course.6.duration': '8 أسابيع',
    'course.6.age': '16+ سنة',
    'event.1.title': 'الأمان الرقمي للآباء',
    'event.1.desc': 'تعلم كيف يمكنك حماية أطفالك عبر الإنترنت وفهم عالمهم الرقمي.',
    'event.1.location': 'المكتبة، المركز',
    'event.2.title': 'مقدمة في الذكاء الاصطناعي للمبتدئين',
    'event.2.desc': 'مقدمة أساسية للذكاء الاصطناعي وكيف يؤثر على حياتنا اليومية.',
    'event.2.location': 'دار الثقافة، القاعة 3',
    'event.3.title': 'البرمجة للأطفال (الصفوف 3-6)',
    'event.3.desc': 'تعلم أساسيات البرمجة من خلال تمارين ممتعة وبسيطة.',
    'event.3.location': 'تيك هب، القاعة الرئيسية',
    'event.4.title': 'وسائل التواصل الاجتماعي - الفوائد والمخاطر',
    'event.4.desc': 'مناقشة مفتوحة حول تأثير وسائل التواصل الاجتماعي على الشباب وكيفية استخدامها بمسؤولية.',
    'event.4.location': 'بيت المواطن',
    'event.5.title': 'دورة الهواتف الذكية لكبار السن',
    'event.5.desc': 'دورة للمبتدئين مهيأة لمن يريدون تعلم كيفية استخدام هواتفهم الذكية بشكل أفضل.',
    'event.5.location': 'مركز كبار السن',
    'event.type.workshop': 'ورشة عمل',
    'event.type.lecture': 'محاضرة',
    'event.type.discussion': 'مناقشة',
    'event.type.course': 'دورة',
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.courses': 'الدورات',
    'nav.events': 'الفعاليات',
    'nav.getInvolved': 'شارك',
    'nav.contact': 'اتصل بنا',

    // Hero
    'hero.title': 'كليك آي تي',
    'hero.subtitle': 'المهارات الرقمية لجميع الأعمار',
    'hero.description': 'نحن نبني جسورًا بين الناس والأدوات الرقمية',
    'hero.cta': 'ابدأ التعلم',
    'hero.learnMore': 'اعرف المزيد',

    // Stats
    'stats.workshops': 'ورش العمل',
    'stats.students': 'الطلاب',
    'stats.volunteers': 'المتطوعون',
    'stats.partners': 'الشركاء',

    // About
    'about.title': 'من نحن',
    'about.subtitle': 'مهمتنا ورؤيتنا',
    'about.description': 'كليك آي تي هي جمعية غير ربحية تأسست من آباء متحمسين. نحن قلقون من أن العديد من الأطفال والشباب وكبار السن يواجهون صعوبات في التعامل مع العالم الرقمي.',
    'about.mission': 'نحن نخلق مسارات آمنة للكفاءة الرقمية ونعمل من أجل حياة رقمية صحية وفعالة وذات معنى - لجميع الأعمار.',
    'about.vision': 'نحن نحلم بعالم يستطيع فيه الجميع، بغض النظر عن العمر، أن يشعروا بالأمان والإبداع في العالم الرقمي.',
    'about.values': 'قيمنا',
    'about.inclusion': 'الشمول',
    'about.inclusion.desc': 'يجب أن تكون المهارات الرقمية متاحة للجميع',
    'about.innovation': 'الابتكار',
    'about.innovation.desc': 'نحن نستكشف طرقًا جديدة للتعلم والنمو',
    'about.community': 'المجتمع',
    'about.community.desc': 'معا نحن أقوى',

    // What We Do
    'whatwedo.title': 'ما نقدمه',
    'whatwedo.subtitle': 'مبادراتنا لمستقبل رقمي',
    'whatwedo.workshops.title': 'ورش عمل المهارات الرقمية',
    'whatwedo.workshops.description': 'ورش عمل عملية توفر أدوات للتعامل مع العالم الرقمي بثقة.',
    'whatwedo.courses.title': 'دورات لجميع الأعمار',
    'whatwedo.courses.description': 'دورات مصممة للأطفال والشباب والبالغين تبني الفهم الرقمي خطوة بخطوة.',
    'whatwedo.collaboration.title': 'التعاون مع المدارس وصناعة تكنولوجيا المعلومات',
    'whatwedo.collaboration.description': 'نحن نخلق جسورًا بين التعليم وقطاع الأعمال لتحسين الكفاءة الرقمية.',
    'whatwedo.elderly.title': 'الدعم الرقمي لكبار السن',
    'whatwedo.elderly.description': 'تركيز خاص على مساعدة كبار السن على الشعور بالثقة مع التكنولوجيا الرقمية.',
    'whatwedo.focus.title': 'التركيز على الصحة والحياة اليومية والمستقبل المهني',
    'whatwedo.focus.description': 'نحن نربط المهارات الرقمية بالاحتياجات الحقيقية في الحياة اليومية وفي المستقبل.',
    'whatwedo.parents.title': 'تعاون وثيق مع الآباء المهتمين',
    'whatwedo.parents.description': 'نحن نشارك بنشاط الآباء والشباب في عمل تطوير الجمعية.',

    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'نود أن نسمع منك',
    'contact.description': 'هل لديك أسئلة أو تريد التعاون؟ لا تتردد في التواصل.',
    'contact.cta': 'هل تريد التعاون أو المساهمة أو مجرد إرسال تحية؟ لا تتردد في التواصل.',
    'contact.email': 'البريد الإلكتروني',
    'contact.address': 'العنوان',
    'contact.addressContent': 'ستوكهولم، السويد',
    'contact.social': 'وسائل التواصل الاجتماعي',
    'contact.form.title': 'أرسل رسالة',
    'contact.form.name': 'الاسم',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.selectSubject': 'اختر موضوعًا',
    'contact.form.subjects.general': 'سؤال عام',
    'contact.form.subjects.courses': 'الدورات',
    'contact.form.subjects.volunteer': 'المشاركة',
    'contact.form.subjects.partner': 'الشراكة',
    'contact.form.subjects.other': 'أخرى',
    'contact.form.submit': 'إرسال الرسالة',
    'contact.form.success': 'شكرًا لرسالتك!',
    'contact.form.successText': 'سنرد عليك في أقرب وقت ممكن.',
    'contact.faq': 'الأسئلة الشائعة',
    'contact.tip': 'نصيحة',
    'contact.tipText': 'نرد عادةً خلال 24 ساعة على جميع الاستفسارات.',
    'contact.closing': 'نبني جسورًا إلى العالم الرقمي',
    'contact.closingText': 'كليك آي تي هو شريكك للكفاءة الرقمية. نؤمن بعالم يمكن فيه الجميع المشاركة في المجتمع الرقمي.',

    // FAQ
    'faq.q1': 'كيف يمكنني التطوع؟',
    'faq.a1': 'املأ نموذج الاهتمام في صفحة "شارك" وسنتواصل معك خلال 48 ساعة.',
    'faq.q2': 'هل يكلف شيء حضور ورش العمل؟',
    'faq.a2': 'لا، جميع ورش العمل والدورات لدينا مجانية تمامًا بفضل رعاتنا ومتبرعينا.',
    'faq.q3': 'ما هي الفئات العمرية التي تستهدفونها؟',
    'faq.a3': 'نرحب بجميع الأعمار! لدينا برامج خاصة للأطفال (8-16) والبالغين وكبار السن (65+).',
    'faq.q4': 'أين تعقدون الأنشطة؟',
    'faq.a4': 'نشاطنا متاح عبر الإنترنت وفي مواقع مختلفة في ستوكهولم. راجع التقويم للحصول على التواريخ الحالية.',

    // Courses Page
    'courses.title': 'دوراتنا',
    'courses.subtitle': 'تعلم المهارات الرقمية بطريقتك',
    'courses.cta': 'اعرف المزيد وسجّل',
    'courses.beginner': 'مبتدئ',
    'courses.intermediate': 'متوسط',
    'courses.advanced': 'متقدم',
    'courses.howItWorks': 'كيف يعمل',
    'courses.steps.register': 'سجّل',
    'courses.steps.choose': 'اختر دورة',
    'courses.steps.learn': 'تعلم',
    'courses.steps.grow': 'نمُ',
    'courses.faq': 'الأسئلة الشائعة',
    'courses.faq.q1': 'ما المتطلبات السابقة؟',
    'courses.faq.a1': 'لا توجد متطلبات سابقة لدورات المبتدئين. نبدأ من الأساسيات!',
    'courses.faq.q2': 'كم تستغرق الدورات؟',
    'courses.faq.a2': 'معظم الدورات تستمر من 4-10 أسابيع بواقع 1-2 جلسة أسبوعيًا.',
    'courses.faq.q3': 'هل يمكنني المشاركة عبر الإنترنت؟',
    'courses.faq.a3': 'نعم، تُقدم كثير من دوراتنا وجهًا لوجه وعبر الإنترنت.',
    'courses.ctaTitle': 'هل أنت مستعد لبدء رحلتك الرقمية؟',
    'courses.ctaText': 'انضم إلى مجتمعنا وتعلم مهارات جديدة معنا',


    // Extra
    'about.learnMore': 'اقرأ المزيد عنا',
    'whatwedo.description': 'نحن نعمل على جعل العالم الرقمي متاحاً للجميع',
    'tags.education': 'التعليم الرقمي',
    'tags.community': 'المجتمع',
    'tags.inclusion': 'الشمول',
    'tags.innovation': 'الابتكار',
    'org.badge': 'منظمتنا',
    'org.title': 'هيكلية من أجل الأثر',
    'org.description': 'نحن منظمون لتحقيق مهمتنا في الشمول الرقمي للجميع بشكل فعال.',
    'org.dept.edu.title': 'التعليم الرقمي',
    'org.dept.edu.desc': 'تطوير المناهج الدراسية وورش العمل التربوية.',
    'org.dept.community.title': 'التواصل المجتمعي',
    'org.dept.community.desc': 'بناء العلاقات مع المجتمعات المحلية والشركاء.',
    'org.dept.support.title': 'الدعم الفني',
    'org.dept.support.desc': 'تقديم المساعدة العملية والتوجيه الفني.',
    'org.dept.innovation.title': 'مختبر الابتكار',
    'org.dept.innovation.desc': 'استكشاف التقنيات الجديدة والأدوات الرقمية.',
    // Events Page
    'events.title': 'الفعاليات',
    'events.subtitle': 'انضم إلى أنشطتنا وورش عملنا',
    'events.upcoming': 'الفعاليات القادمة',
    'events.past': 'الفعاليات السابقة',
    'events.register': 'سجّل',
    'events.suggest': 'اقترح نشاطًا',
    'events.volunteer': 'كن متطوعًا',
    'events.ctaTitle': 'هل تريد تنظيم نشاط؟',
    'events.ctaText': 'نرحب بأفكارك للفعاليات والتعاونيات المستقبلية.',

    // Get Involved Page
    'getInvolved.title': 'شارك',
    'getInvolved.subtitle': 'كن جزءًا من الحركة',
    'getInvolved.description': 'معًا يمكننا إحداث فرق. هناك العديد من الطرق للمساهمة في أنشطة كليك آي تي.',
    'getInvolved.volunteer.title': 'كن متطوعًا',
    'getInvolved.volunteer.description': 'شارك معرفتك وساعد الآخرين على النمو رقميًا. نحتاج إلى مرشدين وقادة ورش عمل ومديري مشاريع.',
    'getInvolved.volunteer.benefit1': 'ساعات مرنة',
    'getInvolved.volunteer.benefit2': 'خبرة قيّمة',
    'getInvolved.volunteer.benefit3': 'فرص للتواصل',
    'getInvolved.donate.title': 'تبرع',
    'getInvolved.donate.description': 'مساعدتك تساعدنا في الوصول إلى المزيد من الناس وتقديم دورات مجانية لمن يحتاجونها أكثر.',
    'getInvolved.donate.benefit1': '100 كرونة = طفل يحصل على دورة كاملة',
    'getInvolved.donate.benefit2': 'ساهم في الشمول الرقمي',
    'getInvolved.donate.benefit3': 'حدث فرقًا في مجتمعك',
    'getInvolved.partner.title': 'شارك كشريك',
    'getInvolved.partner.description': 'يمكن للشركات والمنظمات التعاون معنا لإنشاء مشاريع تعليمية رقمية ذات معنى.',
    'getInvolved.partner.benefit1': 'مشاريع المسؤولية الاجتماعية',
    'getInvolved.partner.benefit2': 'فرص تدريب للشباب',
    'getInvolved.partner.benefit3': 'فرص تطوير للموظفين',
    'getInvolved.school.title': 'التعاون مع المدارس',
    'getInvolved.school.description': 'نتعاون مع المدارس لتقديم التعليم الرقمي للطلاب والمعلمين.',
    'getInvolved.school.benefit1': 'تعليم تكميلي',
    'getInvolved.school.benefit2': 'تدريب المعلمين',
    'getInvolved.school.benefit3': 'مشاريع وورش عمل للطلاب',
    'getInvolved.cta': 'اتصل بنا',
    'getInvolved.ctaTitle': 'هل أنت مستعد للفرق؟',
    'getInvolved.ctaText': 'انضم إلى مجتمعنا وساعدنا في بناء جسور إلى العالم الرقمي.',
    'getInvolved.join': 'انضم الآن',

    // Values
    'values.subtitle': 'ما نؤمن به',
    'values.title': 'قيمنا',
    'values.description': 'نؤمن بعالم يمكن فيه الجميع المشاركة في المجتمع الرقمي.',
    'values.inclusion.title': 'الدعم',
    'values.inclusion.desc': 'نحن ندعم الجميع يريد تعلم المهارات الرقمية',
    'values.innovation.title': 'الابتكار',
    'values.innovation.desc': 'نستكشف طرقًا جديدة للتعلم والنمو معًا',
    'values.community.title': 'المجتمع',
    'values.community.desc': 'معا نحن أقوى في العالم الرقمي',
    'values.learning.title': 'التعلم',
    'values.learning.desc': 'نؤمن بالتعلم المستمر لجميع الأعمار',

    // Footer
    'footer.description': 'نحن نبني جسورًا بين الناس والأدوات الرقمية. المهارات الرقمية لجميع الأعمار.',
    'footer.explore': 'استكشف',
    'footer.contact': 'اتصل بنا',
    'footer.location': 'ستوكهولم، السويد',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.newsletterText': 'احصل على آخر الأخبار حول دوراتنا وفعالياتنا',
    'footer.emailPlaceholder': 'بريدك الإلكتروني',
    'footer.subscribe': 'اشترك',
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'الشروط',
    'event.past.1.title': 'الافتتاح - نحن نبني الجسور',
    'event.past.1.desc': 'الإطلاق الرسمي للجمعية مع كلمات وتواصل ورؤى مستقبلية.',
    'event.past.2.title': 'مخيم البرمجة الصيفي للشباب',
    'event.past.2.desc': 'خمسة أيام مليئة بالبرمجة وتطوير الألعاب والابتكار الرقمي.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children, locale: initialLocale }: { children: ReactNode; locale: string }) {
  const [locale, setLocaleState] = useState<Locale>(normalizeLocale(initialLocale));

  const setLocale = (nextLocale: Locale) => {
    setLocaleState(normalizeLocale(nextLocale));
  };

  const t = (key: string): string => {
    const localeTable = translations[locale] ?? translations[DEFAULT_LOCALE];
    return localeTable[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
